### ISSUE TITLE
The list of devices is loading too slowly

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#58] opened 2015-10-20 11:30 UTC
Load list of device is too long and if count of device increase then time increase too. For example, loading list for 500 devices  reach about 2 minutes

**Comment by KMax** [comment] 2015-10-20 11:35
Yeap, it was expected, because Fuseki is more a toy, than a production ready triplestore. But anyway, I suggest to answer the question "Why did the query become so slow?". I see three options: (a) longer query execution time, (b) longer download time of the query results or (c) both.

**Comment by soylent-grin** [comment] 2015-10-20 12:12
2 minutes is very strange time and isn't normal to Fuseki - we made some benchmarks early for 1000 devices.
I think we should look at Fuseki's log when this behavior is observed - maybe, there are some locks or GC issues

**Comment by garayzuev** [comment] 2015-10-27 16:30
@soylent-grin , I think we can change query from:

```
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ssncom: <http://purl.org/NET/ssnext/communication#>
PREFIX saref: <http://ontology.tno.nl/saref#>
PREFIX mcht: <http://purl.org/NET/ssnext/machinetools#>
PREFIX qudt: <http://www.qudt.org/qudt/owl/1.0.0/qudt/#>
PREFIX qudt-quantity: <http://qudt.org/vocab/quantity#>
PREFIX qudt-unit: <http://qudt.org/vocab/unit#>
PREFIX om: <http://purl.org/ifgi/om#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?label ?uri ?state
WHERE {
   ?uri a ssn:System ;
       a ?type ;
       saref:hasState ?state .
       ?uri rdfs:label ?label .
   FILTER NOT EXISTS {
       ?subClass rdfs:subClassOf ?type .
       ?uri a ?subClass .
       FILTER (?subClass != ?type)
   }
}
```

to 

```
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX saref: <http://ontology.tno.nl/saref#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?label ?uri ?state
WHERE {
   ?uri a ssn:System ;
       saref:hasState ?state ;
       rdfs:label ?label .
}
```

**Comment by KMax** [comment] 2015-10-28 08:34
So looks like @garayzuev found the root cause? Can we implement the fix and close this issue?

**Closed as completed** 2015-10-28 10:05 UTC
Labels: ui
