### ISSUE TITLE
Web-UI should listen for registered device to turn off

### ISSUE THREAD

**Issue by garayzuev** [semiotproject/semiot-platform#20] opened 2015-04-20 16:10 UTC

**Comment by soylent-grin** [comment] 2015-04-27 16:24
See #21

**Comment by KMax** [comment] 2015-10-13 09:27
@garayzuev @soylent-grin  Is it a duplicate of #21 issue?

**Comment by soylent-grin** [comment] 2015-10-13 10:04
No, this task is for webUI, #21 - for DeviceProxy.
BTW, webUI already have [listener](https://github.com/semiotproject/semiot-platform/blob/master/web-ui/src/js/models/system-list.js#L29) for this action - on WAMP topic `ru.semiot.devices.turnoff`

**Closed as completed** 2015-10-19 22:00 UTC
Labels: ui
